language: r
cache: packages

before_install:
  Rscript -e 'update.packages(ask = FALSE)'

matrix: # 2 OS x 3 R versions
  include:
  - os: linux
    r: oldrel
    dist: trusty
  - os: linux
    r: release
    dist: trusty
  - os: linux
    r: devel
    dist: trusty
  - os: osx
    r: release

